name: Push To Discord Channel on Pull Request Closed

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  push-to-discord:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Post Discord
        env:
          EMBEDS: '{ "embeds": [{ "author": { "name": "${{ github.event.pull_request.user.name }}" }, "title": "${{ github.event.pull_request.title }}", "description": "${{ github.event.pull_request.body }}", "color": "${{ vars.DISCORD_EMBED_COLOR }}" }] }'
          DISCORD_WEBHOOK: $ {{ secrets.GDSC_CAU_DISCORD_ARTICLES }}
          DISCORD_EMBEDS: $ {{ toJson(env.EMBEDS) }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "New readings are updated!"
